name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build with Node.js 21.1.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21.1.0

      - name: Install dependencies
        run: npm install

      - name: Run prod script
        run: npm run prod
